[package]
name = "bitwise-challenge-bddap"
version = "0.1.0"
edition = "2024"

[dependencies]
bitwise-challenge = { git = "https://github.com/zesterer/bitwise-examples.git", rev = "b8479bfd485356b3ac399f984e713939ba6a6573", version = "0.1.0" }
